/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.indianstatescensusanalyzer;

import org.junit.Test;

import com.bridgelabz.indianstatescensusanalyzer.CensusAnalyser;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        CensusAnalyser classUnderTest = new CensusAnalyser();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
